
CREATE TABLE dim_customer (
   customer_key      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   customer_id       NUMBER NOT NULL,
   first_name        VARCHAR2(100),
   last_name         VARCHAR2(100),
   gender            VARCHAR2(20),
   email             VARCHAR2(200),
   phone             VARCHAR2(50),
   city              VARCHAR2(100),
   state             VARCHAR2(100),
   country           VARCHAR2(100),
   postal_code       VARCHAR2(20),
   date_of_birth     DATE,
   registration_date DATE,
   record_hash       VARCHAR2(64),
   valid_from        DATE,
   valid_to          DATE,
   is_current        NUMBER(1)
);


CREATE TABLE dim_product (
   product_key     NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
   product_id      NUMBER NOT NULL,
   product_name    VARCHAR2(200),
   sku             VARCHAR2(50),
   description     VARCHAR2(1000),
   price           NUMBER(10,2),
   stock_quantity  NUMBER(10),
   product_status  VARCHAR2(20),
   category_id     NUMBER,
   supplier_id     NUMBER,
   record_hash     VARCHAR2(64),
   valid_from      DATE NOT NULL,
   valid_to        DATE,
   is_current      NUMBER(1) DEFAULT 1
);


CREATE TABLE dim_category (
   category_key    NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
   category_id     NUMBER NOT NULL,
   category_name   VARCHAR2(50),
   description     VARCHAR2(500),
   record_hash     VARCHAR2(64),
   valid_from      DATE NOT NULL,
   valid_to        DATE,
   is_current      NUMBER(1) DEFAULT 1
);


CREATE TABLE dim_supplier (
   supplier_key    NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
   supplier_id     NUMBER NOT NULL,
   supplier_name   VARCHAR2(150),
   contact_name    VARCHAR2(100),
   email           VARCHAR2(150),
   phone           VARCHAR2(20),
   city            VARCHAR2(100),
   state           VARCHAR2(50),
   country         VARCHAR2(50),
   postal_code     VARCHAR2(20),
   record_hash     VARCHAR2(64),
   valid_from      DATE NOT NULL,
   valid_to        DATE,
   is_current      NUMBER(1) DEFAULT 1
);


CREATE TABLE dim_date (
   date_key        NUMBER PRIMARY KEY,
   full_date       DATE NOT NULL,
   year            NUMBER,
   quarter         NUMBER,
   month           NUMBER,
   day_of_month    NUMBER,
   day_of_week     NUMBER,
   month_name      VARCHAR2(20),
   day_name        VARCHAR2(20)
);


-- Fact Table:


CREATE TABLE fact_sales (
   sales_key        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
   order_id         NUMBER NOT NULL,
   order_item_id    NUMBER NOT NULL,
   customer_key     NUMBER NOT NULL,
   product_key      NUMBER NOT NULL,
   category_key     NUMBER NOT NULL,
   supplier_key     NUMBER NOT NULL,
   order_date_key   NUMBER NOT NULL,
   payment_date_key NUMBER,
   quantity         NUMBER(8),
   unit_price       NUMBER(10,2),
   line_total       NUMBER(14,2),
   payment_amount   NUMBER(12,2),
   payment_method   VARCHAR2(30),
   payment_status   VARCHAR2(20)
);






-- Loading DimDate before the etl fact load
-- It is run only once because it is not obtained
-- from oltp tables but populated once
-- in this case, it is populated one row for each
-- day covering the next 10 years (36500 days)


INSERT INTO dim_date (
   date_key,
   full_date,
   year,
   quarter,
   month,
   day_of_month,
   day_of_week,
   month_name,
   day_name
)
SELECT
   TO_NUMBER(TO_CHAR(d, 'YYYYMMDD')),
   d,
   EXTRACT(YEAR FROM d),
   TO_NUMBER(TO_CHAR(d, 'Q')),
   EXTRACT(MONTH FROM d),
   EXTRACT(DAY FROM d),
   TO_NUMBER(TO_CHAR(d, 'D')),
   TO_CHAR(d, 'Month'),
   TO_CHAR(d, 'Day')
FROM (
   SELECT DATE '2010-01-01' + LEVEL - 1 AS d
   FROM dual
   CONNECT BY LEVEL <= 36500   
);


ETL process


-- Creating the staging tables
-- We only grab the table with its attributes but
-- do not populate yet (more on this later).


CREATE TABLE stg_customers AS SELECT * FROM customers WHERE 1=0;
CREATE TABLE stg_products AS SELECT * FROM products WHERE 1=0;
CREATE TABLE stg_categories AS SELECT * FROM categories WHERE 1=0;
CREATE TABLE stg_suppliers AS SELECT * FROM suppliers WHERE 1=0;
CREATE TABLE stg_orders AS SELECT * FROM orders WHERE 1=0;
CREATE TABLE stg_order_items AS SELECT * FROM order_items WHERE 1=0;
CREATE TABLE stg_payments AS SELECT * FROM payments WHERE 1=0;


-- First Layer: Extract
-- We truncate the staging tables first


TRUNCATE TABLE stg_customers;
INSERT INTO stg_customers SELECT * FROM customers;


TRUNCATE TABLE stg_products;
INSERT INTO stg_products SELECT * FROM products;


TRUNCATE TABLE stg_categories;
INSERT INTO stg_categories SELECT * FROM categories;


TRUNCATE TABLE stg_suppliers;
INSERT INTO stg_suppliers SELECT * FROM suppliers;


TRUNCATE TABLE stg_orders;
INSERT INTO stg_orders SELECT * FROM orders;


TRUNCATE TABLE stg_order_items;
INSERT INTO stg_order_items SELECT * FROM order_items;


TRUNCATE TABLE stg_payments;
INSERT INTO stg_payments SELECT * FROM payments;


-- Second Layer: Transform




ALTER TABLE stg_customers ADD record_hash VARCHAR2(64);
ALTER TABLE stg_products ADD record_hash VARCHAR2(64);
ALTER TABLE stg_categories ADD record_hash VARCHAR2(64);
ALTER TABLE stg_suppliers ADD record_hash VARCHAR2(64);




-- Transform for Customers Staging Table


-- Cleaning


UPDATE stg_customers
SET
   first_name        = INITCAP(TRIM(first_name)),
   last_name         = INITCAP(TRIM(last_name)),
   gender            = UPPER(TRIM(gender)),
   email             = LOWER(TRIM(email)),
   phone             = TRIM(phone),
   city              = INITCAP(TRIM(city)),
   state             = UPPER(TRIM(state)),
   country           = INITCAP(TRIM(country)),
   postal_code       = TRIM(postal_code);


-- Validation


DELETE FROM stg_customers
WHERE email NOT LIKE '%@%.%';


-- adding a hash-based attribute to
-- avoid processing records that have not had any
-- changes


UPDATE stg_customers
SET record_hash = LOWER(
   STANDARD_HASH(
       first_name || last_name || gender || email ||
       city || state || country || postal_code,
       'SHA256'
   )
);


-- Transform for Products Staging Table


UPDATE stg_products
SET
   product_name   = INITCAP(TRIM(product_name)),
   sku            = UPPER(TRIM(sku)),
   description    = TRIM(description),
   product_status = UPPER(TRIM(product_status));




-- Validation


DELETE FROM stg_products
WHERE price < 0 OR stock_quantity < 0;


UPDATE stg_products
SET record_hash = LOWER(
   STANDARD_HASH(
       product_name || sku || price || product_status ||
       stock_quantity || category_id || supplier_id,
       'SHA256'
   )
);


-- Transform for the Categories Staging Table


UPDATE stg_categories
SET
   category_name = INITCAP(TRIM(category_name)),
   description   = TRIM(description);


UPDATE stg_categories
SET record_hash = LOWER(
   STANDARD_HASH(
       category_name || description,
       'SHA256'
   )
);


-- Transform for the Suppliers Staging Table


UPDATE stg_suppliers
SET
   supplier_name = INITCAP(TRIM(supplier_name)),
   contact_name  = INITCAP(TRIM(contact_name)),
   email         = LOWER(TRIM(email)),
   phone         = TRIM(phone),
   city          = INITCAP(TRIM(city)),
   state         = UPPER(TRIM(state)),
   country       = INITCAP(TRIM(country)),
   postal_code   = TRIM(postal_code);


-- Validation


DELETE FROM stg_suppliers
WHERE email IS NOT NULL AND email NOT LIKE '%@%.%';


UPDATE stg_suppliers
SET record_hash = LOWER(
   STANDARD_HASH(
       supplier_name || contact_name || email || phone ||
       city || state || country || postal_code,
       'SHA256'
   )
);


-- Transform for the Orders Staging Table


UPDATE stg_orders
SET
   order_status = UPPER(TRIM(order_status));


-- Validation


DELETE FROM stg_orders
WHERE total_amount < 0;


-- Transform for the Order Items Staging Table


UPDATE stg_order_items
SET
   quantity   = quantity,
   unit_price = unit_price;




-- Validation


DELETE FROM stg_order_items
WHERE quantity <= 0 OR unit_price < 0;


-- Transform for the Payments Staging Table


UPDATE stg_payments
SET
   payment_method = UPPER(TRIM(payment_method)),
   payment_status = UPPER(TRIM(payment_status)),
   transaction_ref = TRIM(transaction_ref);


-- Validation


DELETE FROM stg_payments
WHERE amount < 0;




-- Loading phase


-- Loading Dim Customer


MERGE INTO dim_customer d
USING stg_customers s
ON (d.customer_id = s.customer_id)


WHEN MATCHED THEN
   UPDATE SET
       d.valid_to = SYSDATE,
       d.is_current = 0
   WHERE d.is_current = 1
     AND d.record_hash <> s.record_hash


WHEN NOT MATCHED THEN
   INSERT (
       customer_id,
       first_name, last_name, gender, email,
       phone, city, state, country, postal_code,
       date_of_birth, registration_date,
       record_hash,
       valid_from, valid_to, is_current
   )
   VALUES (
       s.customer_id,
       s.first_name, s.last_name, s.gender, s.email,
       s.phone, s.city, s.state, s.country, s.postal_code,
       s.date_of_birth, s.registration_date,
       s.record_hash,
       SYSDATE, NULL, 1
   );


-- Loading Dim Product


MERGE INTO dim_product d
USING stg_products s
ON (d.product_id = s.product_id)


WHEN MATCHED THEN
   UPDATE SET
       d.valid_to = SYSDATE,
       d.is_current = 0
   WHERE d.is_current = 1
     AND d.record_hash <> s.record_hash


WHEN NOT MATCHED THEN
   INSERT (
       product_id,
       product_name, sku, description, price,
       stock_quantity, product_status,
       category_id, supplier_id,
       record_hash,
       valid_from, valid_to, is_current
   )
   VALUES (
       s.product_id,
       s.product_name, s.sku, s.description, s.price,
       s.stock_quantity, s.product_status,
       s.category_id, s.supplier_id,
       s.record_hash,
       SYSDATE, NULL, 1
   );


-- Loading Dim Category


MERGE INTO dim_category d
USING stg_categories s
ON (d.category_id = s.category_id)


WHEN MATCHED THEN
   UPDATE SET
       d.valid_to = SYSDATE,
       d.is_current = 0
   WHERE d.is_current = 1
     AND d.record_hash <> s.record_hash


WHEN NOT MATCHED THEN
   INSERT (
       category_id,
       category_name, description,
       record_hash,
       valid_from, valid_to, is_current
   )
   VALUES (
       s.category_id,
       s.category_name, s.description,
       s.record_hash,
       SYSDATE, NULL, 1
   );


MERGE INTO dim_supplier d
USING stg_suppliers s
ON (d.supplier_id = s.supplier_id)


WHEN MATCHED THEN
   UPDATE SET
       d.valid_to = SYSDATE,
       d.is_current = 0
   WHERE d.is_current = 1
     AND d.record_hash <> s.record_hash


WHEN NOT MATCHED THEN
   INSERT (
       supplier_id,
       supplier_name, contact_name, email, phone,
       city, state, country, postal_code,
       record_hash,
       valid_from, valid_to, is_current
   )
   VALUES (
       s.supplier_id,
       s.supplier_name, s.contact_name, s.email, s.phone,
       s.city, s.state, s.country, s.postal_code,
       s.record_hash,
       SYSDATE, NULL, 1
   );


-- Loading the fact table


INSERT INTO fact_sales (
   order_id,
   order_item_id,
   customer_key,
   product_key,
   category_key,
   supplier_key,
   order_date_key,
   payment_date_key,
   quantity,
   unit_price,
   line_total,
   payment_amount,
   payment_method,
   payment_status
)
SELECT
   oi.order_id,
   oi.order_item_id,


   dc.customer_key,
   dp.product_key,
   dcat.category_key,
   dsup.supplier_key,


   TO_NUMBER(TO_CHAR(o.order_date, 'YYYYMMDD')),
   TO_NUMBER(TO_CHAR(p.payment_date, 'YYYYMMDD')),


   oi.quantity,
   oi.unit_price,
   oi.line_total,


   p.amount,
   p.payment_method,
   p.payment_status
FROM stg_order_items oi
JOIN stg_orders o
   ON oi.order_id = o.order_id
JOIN stg_products pr
   ON oi.product_id = pr.product_id
LEFT JOIN stg_payments p
   ON oi.order_id = p.order_id


JOIN dim_customer dc
   ON o.customer_id = dc.customer_id
  AND dc.is_current = 1


JOIN dim_product dp
   ON pr.product_id = dp.product_id
  AND dp.is_current = 1


JOIN dim_category dcat
   ON pr.category_id = dcat.category_id
  AND dcat.is_current = 1


JOIN dim_supplier dsup
   ON pr.supplier_id = dsup.supplier_id
  AND dsup.is_current = 1;
